--cálculo de CMV
SELECT
       C.CODEMP,
       E.NOMEFANTASIA,
       C.CODPARC,
       P.NOMEPARC,
       C.CODTIPOPER,
       I.CODVOL,
       T.DESCROPER,
       C.CODPROJ,
       PRJ.IDENTIFICACAO,
       C.DTNEG,
       C.DTENTSAI,
       C.DTPREVENT,
       I.CODPROD,
       PRO.REFERENCIA,
       PRO.DESCRPROD,
       PRO.NCM,
       PRO.CODGRUPOPROD AS CODGRUPOPROD,
       G.DESCRGRUPOPROD AS DESCRGRUPOPROD,
       (SELECT PAI.DESCRGRUPOPROD FROM TGFGRU PAI WHERE PAI.CODGRUPOPROD = G.CODGRUPAI) AS DESGRUPAI,
       PRO.MARCA,
       I.VLRUNIT,
       I.QTDNEG * I.VLRUNIT AS VLRTOTCALC,
       I.VLRTOT,
       I.VLRUNITMOE,
       I.VLRTOTMOE,
       I.QTDNEG,
       C.NUNOTA,
       C.NUMNOTA,
       C.CODCENCUS,
       CUS.DESCRCENCUS,
       C.CODNAT,
       N.DESCRNAT,

       -- DADOS NATIVOS DO SANKHYA PARA A PLANILHA DE IMPORTAÇÃO
       PRO.M3 AS CUBAGEMPROD,
       (I.QTDNEG * PRO.M3) AS CUBAGEMPEDITEM,
       C.VLRFRETE,
       C.AD_QTDCONTAINER,
       C.AD_TIPOCONTAINER AS TAMANHO_CTN,
       ROUND(C.VLRMOEDA, 2) AS TX_CAMBIO_PEDIDO, 
       I.ALIQIPI AS PERC_IPI,
       (SELECT MAX(D.ALIQUOTA) FROM TGFDIN D WHERE D.NUNOTA = I.NUNOTA AND D.SEQUENCIA = I.SEQUENCIA AND D.CODIMP = 6) AS PERC_PIS,
       (SELECT MAX(D.ALIQUOTA) FROM TGFDIN D WHERE D.NUNOTA = I.NUNOTA AND D.SEQUENCIA = I.SEQUENCIA AND D.CODIMP = 7) AS PERC_COFINS,
       0.00 AS PERC_II, 

       -- COLUNAS RESERVADAS PARA FÓRMULAS
       0.00 AS CUB_CTN,
       0.00 AS VLR_FRETE_USD,
       0.00 AS PERC_CTN,
       0.00 AS VLR_FRETE_BRL,
       0.00 AS THC_USD,
       0.00 AS VALOR_FOB_NUM,
       0.00 AS VA_BRL,
       0.00 AS VLR_II,
       0.00 AS VLR_IPI,
       0.00 AS VLR_PIS,
       0.00 AS VLR_COFINS,
       
        -- COTAÇÃO DO RENMINBI HONG K. CNY TRATADA PARA DATAS FUTURAS / HORÁRIO FECHAMENTO
       (SELECT COT.COTACAO 
          FROM TSICOT COT 
         WHERE COT.CODMOEDA = 8 
           AND COT.DTMOV = (SELECT MAX(COT2.DTMOV) 
                             FROM TSICOT COT2 
                            WHERE COT2.CODMOEDA = 8 
                              AND COT2.DTMOV <= LEAST(TRUNC(NVL(C.DTPREVENT, C.DTNEG)), TRUNC(SYSDATE)))) AS RMB_PTAX,
       
       -- COTAÇÃO DO DÓLAR TRATADA PARA DATAS FUTURAS / HORÁRIO FECHAMENTO
       (SELECT COT.COTACAO 
          FROM TSICOT COT 
         WHERE COT.CODMOEDA = 1 
           AND COT.DTMOV = (SELECT MAX(COT2.DTMOV) 
                             FROM TSICOT COT2 
                            WHERE COT2.CODMOEDA = 1 
                              AND COT2.DTMOV <= LEAST(TRUNC(NVL(C.DTPREVENT, C.DTNEG)), TRUNC(SYSDATE)))) AS DOLAR_PTAX,
                              
       -- COTAÇÃO DO EURO TRATADA PARA DATAS FUTURAS / HORÁRIO FECHAMENTO
       (SELECT COT.COTACAO 
          FROM TSICOT COT 
         WHERE COT.CODMOEDA = 6 
           AND COT.DTMOV = (SELECT MAX(COT2.DTMOV) 
                             FROM TSICOT COT2 
                            WHERE COT2.CODMOEDA = 6 
                              AND COT2.DTMOV <= LEAST(TRUNC(NVL(C.DTPREVENT, C.DTNEG)), TRUNC(SYSDATE)))) AS EURO_PTAX,
                              
       0.00 AS TX_SISC,
       0.00 AS LIB_BL,
       0.00 AS AFMM,
       0.00 AS DESCONSOLIDACAO,
       0.00 AS ARMAZENAGEM,
       0.00 AS FRETE_ROD,
       0.00 AS OUTROS,
       0.00 AS TOTAL_R$,
       0.00 AS R$_UNIDADE,
       DECODE(C.STATUSNOTA, 'L', 'Sim', 'Não') AS CONFIRMADA,
       CASE
            WHEN EXISTS (
                SELECT 1
                  FROM TGFFIN F
                 WHERE F.NUNOTA = C.NUNOTA
                   AND F.AD_DESPGERADA = 'S'
            ) THEN 'Sim'
            ELSE 'Não'
       END AS FINANCEIRO,
       '#DCDCDC' AS BKCOLOR,
       '#006400' AS FGCOLOR,
       CASE WHEN C.CODMOEDA = 0 THEN NULL ELSE C.CODMOEDA || ' - ' || MOE.NOMEMOEDA END AS "Moeda",
       C.PENDENTE

  FROM TGFCAB C
 INNER JOIN TGFITE I   ON C.NUNOTA = I.NUNOTA
 INNER JOIN TSIEMP E   ON C.CODEMP = E.CODEMP
 INNER JOIN TGFPAR P   ON C.CODPARC = P.CODPARC
 INNER JOIN TGFTOP T   ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
 INNER JOIN TGFPRO PRO ON I.CODPROD = PRO.CODPROD
  LEFT JOIN TGFGRU G   ON PRO.CODGRUPOPROD = G.CODGRUPOPROD
  LEFT JOIN TSICUS CUS ON C.CODCENCUS = CUS.CODCENCUS
  LEFT JOIN TGFNAT N   ON C.CODNAT = N.CODNAT
  LEFT JOIN TCSPRJ PRJ ON C.CODPROJ = PRJ.CODPROJ
  LEFT JOIN TSIMOE MOE ON C.CODMOEDA = MOE.CODMOEDA

 WHERE C.TIPMOV = 'O'
   AND (C.CODPROJ = 100252056);-- OR :CODPROJ IS NULL)
   
