SELECT TSIMOE.CODINTMOEDA AS CODINTMOEDA,
       TSIMOE.CODMOEDA    AS CODMOEDA,
       TSIMOE.CODTABBCB   AS CODTABBCB,
       TSIMOE.NOMEMOEDA   AS NOMEMOEDA,
       TSIMOE.TIPCALC     AS TIPCALC,
       TSIMOE.TIPMOEDA    AS TIPMOEDA,
       TSIMOE.TIPOTAXA    AS TIPOTAXA /*SQL_92_JOINED_FIELDS*/
  FROM TSIMOE /*SQL_92_JOINED_TABLES*/
 WHERE ((TSIMOE.CODMOEDA > 0))



SELECT TSICOT.CODMOEDA   AS CODMOEDA,
       TSICOT.COTACAO    AS COTACAO,
       TSICOT.DTMOV      AS DTMOV,
       TSICOT.INDICE2    AS INDICE2,
       TSICOT.INDICEDESC AS INDICEDESC,
       Moeda.NOMEMOEDA   AS l0_NOMEMOEDA
  FROM TSICOT
  left join (SELECT NOMEMOEDA, CODMOEDA FROM TSIMOE) Moeda
    ON (TSICOT.CODMOEDA = Moeda.CODMOEDA)
 WHERE TSICOT.CODMOEDA IN (1,6,8)
 AND TSICOT.DTMOV >= DATE '2026-03-16' order by cotacao desc
